### PR TITLE
Adding the ability to configure imgpkg timeout

### LINKED ISSUE #329: Timeouts when attempting to use vendir with a registry with a significant amount of tags
**What steps did you take:**
When attempting to use a `vendir sync` from a repository with a significant number of files there will be timeouts with no way to handle them.
With imgpkg natively you can use `--registry-response-header-timeout`, but that API isn't exposed here in vendir.

**What happened:**
The sync will timeout.

**What did you expect:**
That as a user I could extend the timeout as long as I need to be able to make it so the request won't time out.

**Environment:**

- vendir version (execute `vendir --version`): 0.35.0
- OS (e.g. from `/etc/os-release`): MacOS (ARM)

**Example config**
```(yaml)
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  # Use this if you're downloading manifests directly from a location.
  - path: bundle/packages.temp
    contents:
      - path: .
        imgpkgBundle:
          image: REPO.COM/IMAGE-REPO
          tagSelection:
            semver:
              constraints: ">1.1.0 <1.7.1"
        newRootPath: packages
  - path: bundle/.imgpkg
    contents:
      - path: .
        imgpkgBundle: *tap
        newRootPath: .imgpkg
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by alexbarbato**
Potentially closes #329 

Looking for feedback if this solution doesn't appear right to you all. Thanks!

### CODE REVIEW

**Review by joaopapereira — CHANGES_REQUESTED** [review]
This looks good, but you need to sign your commits to fix the DCO issue.

You just need to do `git commit -S` and we should be good to accept this PR.

**Comment by alexbarbato** [comment]
Doh, i do that everytime. Thanks! Updated @joaopapereira

**Comment by praveenrewar** [comment]
@alexbarbato The DCO check is still failing 😅

**Comment by alexbarbato** [comment]
> git commit -S

@joaopapereira trying to trick me :P I think it's `-s`

Should work now, but please let me know if I'm still goofing something up!

**Comment by praveenrewar** [comment]
> @joaopapereira trying to trick me :P I think it's -s

Lol, yes, it should be `-s`.

**Review by praveenrewar — COMMENTED** [review]
LGTM!

**Comment by alexbarbato** [comment]
@joaopapereira anything you need here to merge?

**Review by joaopapereira — APPROVED** [review]
LGTM.
We will need a PR in https://github.com/carvel-dev/carvel/ to add the new field to the documentation

**Pull request merged**
