### PR TITLE
[hg] add evolve support

### PR DESCRIPTION
**Pull request by WnP**
This PR follow #110

### CODE REVIEW

**Comment by WnP** [comment]
Ci error say:

```
example.go:27: [example: hg] Expected no diff, but was: >>>diff --git a/examples/hg/vendir.lock.yml b/examples/hg/vendir.lock.yml
```
But I did not modify this file :thinking:

**Comment by cppforlife** [comment]
@WnP let me take a look at the failure (probably not related)

**Comment by neil-hickey** [comment]
hey there @WnP I created a PR which fixes the tests - https://github.com/vmware-tanzu/carvel-vendir/pull/121 

Once that is merged, your PR test should pass

**Comment by WnP** [comment]
Thanks @neil-hickey :-)

**Comment by cppforlife** [comment]
great to see you back @WnP !

**Pull request merged**
