### PR TITLE
add option for skipping SSL verification

### PR DESCRIPTION
**Pull request by vmunishwar**
To fix the issue - https://github.com/carvel-dev/vendir/issues/260

### CODE REVIEW

**Comment by kumaritanushree** [comment]
Changes looks good to me. It will be good if we can add test for the same if possible.

**Comment by varshapm** [comment]
@joaopapereira @kumaritanushree - I have tested the changes and they are working fine on a local gitlab server.

**Comment by vmunishwar** [comment]
@joaopapereira @kumaritanushree - I have tested the changes and they are working fine on a local gitlab server created with a self signed certificate

**Review by joaopapereira — APPROVED** [review]
LGTM

**Comment by vmunishwar** [comment]
Steps to reproduce locally: 
1. Use docker image at https://github.com/danieleagle/gitlab-https-docker/tree/master to start local git lab server. Create a repo.
2. Create self signed certificate using openssl and configure with the server
3. Test vendir sync - It should give an error 'SSL certificate problem: self signed certificate'
4. Tested the fix by adding skipSslVerfication: true. There is no error and repo gets cloned successfully.

**Comment by kumaritanushree** [comment]
LGTM

**Pull request merged**
